rutasappbundle:
    path: /hola/mundo
    defaults: { _controller: AppBundle:Prueba:ver }

rutaparametro:
    path: /prueba/{lang}/{name}/{page}
    defaults: { _controller: AppBundle:Prueba:name,lang:es,name:nombre_por_defecto,page:1 }
    methods: [GET]
    requirements:
        page: \d+
        name: "[a-zA-Z]*"
        lang: es|en|fr

variablesgetypost:
    path: /getypost
    defaults: { _controller: AppBundle:Prueba:variablesgetypost}
    methods: [POST, GET]

twigarrays:
    path: /twigarrays
    defaults: {_controller: AppBundle:Prueba:enviarproductos}

create:
    path: /addcurso
    defaults: {_controller: AppBundle:Prueba:create}

read:
    path: /getcurso
    defaults: {_controller: AppBundle:Prueba:read }

update:
    path: /updatecurso/{id}/{titulo}/{descripcion}/{precio}
    defaults: {_controller: AppBundle:Prueba:update }

delete:
    path: /deletecurso/{id}
    defaults: {_controller: AppBundle:Prueba:delete }

sqlnativo:
    path: /sqlnativo
    defaults: {_controller: AppBundle:Prueba:sqlnativo }

dql:
    path: /dql
    defaults: {_controller: AppBundle:Prueba:dql }

querybuilder:
    path: /querybuilder
    defaults: {_controller: AppBundle:Prueba:querybuilder }